env:
  - NODE_ENV="production"
language: node_js
services:
  - docker
before_install:
  # Create a master branch for commitlint
  # https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches --add origin master && git fetch
install: NODE_ENV=development npm ci
jobs:
  include:
    - stage: Node 12 Tests
      node_js:
        - "12"
      script: npm run test:lint && npm run test:unit && npm run test:danger && npm run test:git-history
      - script: ./scripts/run-integration-tests.travis.sh
        name: "Integration Tests"
    - stage: Node 14 unit tests
      node_js:
        - "14"
      script: npm run test:unit