env:
  - NODE_ENV="production"
language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  # Create a master branch for commitlint
  # https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches --add origin master && git fetch
install: NODE_ENV=development npm ci
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests on macOS"
      os: osx
      script: npm run test:lint && npm run test:unit && npm run test:danger && npm run test:git-history
    - name: "Unit Tests on Windows"
      git:
        autocrlf: input
      os: windows
      script: npm run test:lint && npm run test:unit && npm run test:danger && npm run test:git-history
    - name: "Unit Tests on Linux"
      os: linux
      script: npm run test:lint && npm run test:unit && npm run test:danger && npm run test:git-history
    - name: "Integration Tests"
      script: ./scripts/run-integration-tests.travis.sh
