name: One App Integration Tests
on:
 push:
   branches:
    - main
    - prepare-release
jobs:
  one-app-integration:
    name:  One App Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: NODE_ENV=development npm ci
      - name: Build docker image
        run: docker build -t one-app:at-test . --build-arg USER=root
      - name: Build Sample Modules
        env:
         SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
         SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run:  |
         npm run build:sample-modules -- --archive-built-artifacts --bundle-statics-origin=${{ secrets.SURGE_DOMAIN }}
         echo '${{ secrets.HEROKU_APP_URL }}' >> sample-module-bundles/CORS
      - name: Teardown Surge
        env:
         SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
         SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: npx surge teardown ${{ secrets.SURGE_DOMAIN }}
      - name: Move sample modules to Surge
        env:
         SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
         SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: npx surge sample-module-bundles ${{ secrets.SURGE_DOMAIN }}
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Docker Tag
        run: docker tag one-app:at-test registry.heroku.com/${{ secrets.HEROKU_APP_ID }}/web
      - name: Docker Push
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_ID }}/web
      - name: Heroku Release Image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_ID }}
      - name: Run Integration Tests on Heroku
        run: ONE_DANGEROUSLY_SKIP_ONE_APP_IMAGE_BUILD=true npm run test:integration -- --remote-one-app-environment=${{ secrets.HEROKU_APP_URL }}
