# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    strategy:
      matrix:
        node-version: [12.16.3]

    steps:
    # setup
    - uses: actions/checkout@v2
    - run: git remote set-branches --add origin master && git fetch
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: NODE_ENV=development npm ci
    - run: npm run build --if-present
    # - run: sh prod-sample/setup-docker.sh
    # - run: npm run build:prod-sample
    - run: prod-sample/setup-prod-sample.sh
    # tests
    - run: npm run test:git-history
    - run: npm run test:lockfile
    - run: npm run test:lint
    - run: npm run test:unit
    -
      env:
        JEST_TEST_REPORT_PATH: ./test-results/integration-test-report.html
      run: node_modules/.bin/jest --config jest.integration.config.js --forceExit
    # - run: npm run build:prod-sample
    # - run: npm run test:integration
    - run: echo "TODO:performance"
    - run: echo "TODO:reporter"
